# Coins to watch
watchlist: ['DOGEUSDT']

# Amount of data relative to maximum interval to download. ( max_interval + precision )
precision: 1000

# Time intervals to watch token
time_intervals:
  - 1m

# Exponential moving average intervals
ema_intervals:
  - 9
  - 13
  - 21
  - 55
